[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NEXT_FORCE_EDGE_RUNTIME = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force dynamic routes to be client-side rendered
[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/signup-confirmation"
  to = "/signup-confirmation/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/courses"
  to = "/courses/index.html"
  status = 200
  force = true

# Add redirects to handle OAuth errors at the root path
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  query = {error = ":error", error_code = ":error_code"}
  force = true

[[redirects]]
  from = "/login"
  to = "/login/index.html" 
  status = 200
  force = true